# 1. Configurações de Conexão com o MySQL
# (Note que coloquei a porta 3307 que configuramos e o nome do banco bbb_votacao)
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3307/bbb_votacao?useTimezone=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Configurações do Hibernate (O tradutor de Java para SQL)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true