# URL de conexão (substitua pelo host e porta que aparecem na sua tela)
spring.datasource.url=jdbc:mysql://mysql-3ff9ba06-sistemadevotacao.b.aivencloud.com:13781/defaultdb?ssl-mode=REQUIRED

# Usuário (provavelmente avnadmin)
spring.datasource.username=avnadmin

# Senha (clique em REVELAR_SENHA na sua tela e cole aqui)
spring.datasource.password=AVNS_Yj3MtqmK3LfrJ1goy_-

# Driver e Hibernate
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true